# Generated by Django 4.2.4 on 2024-03-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_transaction_deposit_transaction_new_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='new_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer',
        ),
    ]
