# Generated by Django 4.2.4 on 2024-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_transaction_email_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(default='static/images/avatars/blank-profile-picture.png', upload_to='profile_pictures'),
        ),
    ]
